export default {
    // logo
    Logo: require('../src/assets/img/logo/CodenUILogo.svg'),
    Avatar: require("../src/assets/img/icon/Avatar-icon.svg"),
    DownArrow: require("../src/assets/img/icon/downArrow.svg"),
    RightArrow: require("../src/assets/img/icon/right_arrow.svg"),
    // social 
    Facebook: require("../src/assets/img/icon/facebook.svg"),
    Twitter: require("../src/assets/img/icon/Twitter.svg"),
    LinkedIn: require("../src/assets/img/icon/Linkedin.svg"),
    Instagram: require("../src/assets/img/icon/Instagram.svg"),
    // others
    Bootstrap: require("../src/assets/img/icon/Bootstrap-icon.svg"),
    Figma: require("../src/assets/img/icon/Figma-icon.svg"),
    Gatsby: require("../src/assets/img/icon/Gatsby-icon.svg"),
    HTML: require("../src/assets/img/icon/HTML-icon.svg"),
    NextJs: require("../src/assets/img/icon/nextjs-icon.svg"),
    Tailwind: require("../src/assets/img/icon/Tailwind-css-icon.svg"),
    VueJs: require("../src/assets/img/icon/vueJs-icon.svg"),
    WebFlow: require("../src/assets/img/icon/Webflow-icon.svg"),
    CodedBlocks2: require("../src/assets/img/media/coded-blocks-2.jpg"),
    CodedBlocksPre: require("../src/assets/img/media/coded-blocks-pre.jpg"),
    WebKit: require("../src/assets/img/coded_templates/web_kit_1.svg"),
    FigmaSq: require("../src/assets/img/icon/Figma-sq.svg"),
    PngIconSq: require("../src/assets/img/icon/png-icon-sq.svg"),
    PopupIcon: require("../src/assets/img/icon/popup-icon.svg"),
    BackIcon: require("../src/assets/img/icon/single-icon-pack-back.svg"),
    SvgIconSq: require("../src/assets/img/icon/svg-icon-sq.svg"),
    AddWallet: require("../src/assets/img/icon/wallet-add.svg"),
    WebFlowSq: require("../src/assets/img/icon/Webflow-sq.svg")
}